const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
(async()=>{
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('file://'+path.resolve('app/src/main/assets/index.html'));
await page.click('button[type=submit]');assert.match(await page.locator('#error').textContent(),/모두 입력/);
await page.click('#example');await page.click('button[type=submit]');
assert.equal(await page.locator('#total').textContent(),'166.1 점');
assert.match(await page.locator('#survival').textContent(),/64%/);
assert.equal(await page.locator('.metric').count(),5);
await page.screenshot({path:'../output/mCRPC_Nomogram_Screen.png',fullPage:true});
await page.locator('#psa').fill('0');assert.equal(await page.locator('#result').isVisible(),false);
await page.click('button[type=submit]');assert.match(await page.locator('#error').textContent(),/psa/);
await page.click('#reset');assert.equal(await page.locator('#psa').inputValue(),'');
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
await page.setViewportSize({width:320,height:640});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
assert.deepEqual(errors,[]);
await browser.close();console.log('PASS: UI empty input, example, results, stale result clearing, invalid PSA, reset, 320/390 px layout');
})().catch(e=>{console.error(e);process.exit(1);});
